M48
; DRILL file {KiCad 9.0.2} date 2025-07-31T20:28:15-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-31T20:28:15-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X72.79Y-113.345
X78.57Y-113.345
T2
X56.0Y-56.0
X94.0Y-114.0
M30
